# Generated by Django 2.1.7 on 2019-03-31 00:39

import data.models.tech_group
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to=data.models.tech_group.tech_group_folder, verbose_name='logo')),
            ],
            options={
                'verbose_name': 'group',
            },
        ),
    ]
