# Generated by Django 2.1.7 on 2019-03-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_techgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
