# Generated by Django 2.2.2 on 2019-07-06 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190331_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('tech_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.TechGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'date_joined'],
                'unique_together': {('tech_group', 'user')},
            },
        ),
        migrations.AddField(
            model_name='techgroup',
            name='members',
            field=models.ManyToManyField(through='data.Membership', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
    ]
